In [14]:
import pandas as pd 

from sklearn.preprocessing import OneHotEncoder

In [15]:
# create a simple dataframe

df = pd.DataFrame({
    'color': ['red','blue', 'green', 'green', 'red', 'blue']    
})

In [16]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [17]:
## create an instance of oneHotEncoder

encoder = OneHotEncoder()

In [18]:
# perform fit and transform

encoded = encoder.fit_transform(df[['color']]).toarray()

In [19]:
import pandas as pd

encoder_df = pd.DataFrame(encoded, columns=encoder.get_feature_names_out())

encoder_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [20]:
# when you got new data then what will happen

encoder.transform([['blue']]).toarray()

d:\Projects\MachineLearning_Practise\venv\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

In [21]:
pd.concat([df, encoder_df], axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5   blue         1.0          0.0        0.0

In [ ]:
import seaborn as sns

sns.load_dataset('tips')

# and ther are sex, smoker, day and time so do with thatm

NameError: name 'sns' is not defined