# 3.Target Encoding

In [1]:
import pandas as pd

df = pd.DataFrame({
    'city': ['New York', 'London', 'Paris', 'Tokyo', 'New York', 'Paris'],
    'price': [200, 150, 300, 250, 180, 320]
})

In [3]:
mean_price = df.groupby('city')['price'].mean().to_dict()

mean_price

{'London': 150.0, 'New York': 190.0, 'Paris': 310.0, 'Tokyo': 250.0}

In [6]:
df['city_encoded'] = df['city'].map(mean_price)

df

       city  price  city_encoded
0  New York    200         190.0
1    London    150         150.0
2     Paris    300         310.0
3     Tokyo    250         250.0
4  New York    180         190.0
5     Paris    320         310.0

In [9]:
import seaborn as sns
import pandas as pd
df = sns.load_dataset('tips')

df[['time', 'total_bill']].head()

     time  total_bill
0  Dinner       16.99
1  Dinner       10.34
2  Dinner       21.01
3  Dinner       23.68
4  Dinner       24.59

In [ ]:
# Lunch aur Dinner ka average bill calculate karke dictionary banayein
mean_time_dict = df.groupby('time')['total_bill'].mean().to_dict()

mean_time_dict

# (Yani Lunch ka average bill lagbhag ₹17.16 hai aur Dinner ka ₹20.79).

{'Lunch': 17.168676470588235, 'Dinner': 20.79715909090909}

In [13]:
# map() function use karke naya column banaye

df['time_encoded'] = df['time'].map(mean_time_dict)

df[['time', 'total_bill', 'time_encoded']].head()

     time  total_bill time_encoded
0  Dinner       16.99    20.797159
1  Dinner       10.34    20.797159
2  Dinner       21.01    20.797159
3  Dinner       23.68    20.797159
4  Dinner       24.59    20.797159

In [14]:
# Order nikalna mean ke hisab se
ordered_labels = df.groupby('time')['total_bill'].mean().sort_values().index

# Rank dictionary: {'Lunch': 1, 'Dinner': 2}
rank_dict = {k: i for i, k in enumerate(ordered_labels, 1)}

# Map karna
df['time_rank_encoded'] = df['time'].map(rank_dict)

df[['time', 'total_bill', 'time_encoded', 'time_rank_encoded']].head()

     time  total_bill time_encoded time_rank_encoded
0  Dinner       16.99    20.797159                 2
1  Dinner       10.34    20.797159                 2
2  Dinner       21.01    20.797159                 2
3  Dinner       23.68    20.797159                 2
4  Dinner       24.59    20.797159                 2